apiVersion: v1
data:
  database-name: c2FtcGxlZGI=
  database-password: RTQxaklpbExiTGhZOHRTSg==
  database-root-password: TGdzSmlBeUxYZVUxZHJEMA==
  database-user: dXNlck0wTA==
kind: Secret
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
    template.openshift.io/expose-database_name: '{.data[''database-name'']}'
    template.openshift.io/expose-password: '{.data[''database-password'']}'
    template.openshift.io/expose-root_password: '{.data[''database-root-password'']}'
    template.openshift.io/expose-username: '{.data[''database-user'']}'
  creationTimestamp: "2022-03-22T08:12:21Z"
  labels:
    app: mariadb-ephemeral
    app.kubernetes.io/component: mariadb-ephemeral
    app.kubernetes.io/instance: mariadb-ephemeral
    template: mariadb-ephemeral-template
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:database-name: {}
        f:database-password: {}
        f:database-root-password: {}
        f:database-user: {}
      f:metadata:
        f:annotations:
          .: {}
          f:openshift.io/generated-by: {}
          f:template.openshift.io/expose-database_name: {}
          f:template.openshift.io/expose-password: {}
          f:template.openshift.io/expose-root_password: {}
          f:template.openshift.io/expose-username: {}
        f:labels:
          .: {}
          f:app: {}
          f:app.kubernetes.io/component: {}
          f:app.kubernetes.io/instance: {}
          f:template: {}
      f:type: {}
    manager: oc
    operation: Update
    time: "2022-03-22T08:12:21Z"
  name: mariadb
  namespace: mariadb
  resourceVersion: "4089966"
  selfLink: /api/v1/namespaces/mariadb/secrets/mariadb
  uid: 7903e72a-f5c7-4169-9064-f0388ec0be0e
type: Opaque
